In [1]:
import torch
import numpy as np

In [2]:
torch.tensor([[1,2,3]])

tensor([[1, 2, 3]])

In [3]:
a = torch.rand(2,3)
b = np.random.rand(2,3)

In [4]:
a

tensor([[0.6202, 0.4794, 0.9292],
        [0.2219, 0.5270, 0.5386]])

In [5]:
b

array([[0.93020742, 0.50018971, 0.77417404],
       [0.94747321, 0.86304109, 0.31629793]])

In [6]:
a=torch.tensor([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

tensor([[1, 2, 3],
        [4, 5, 6]])
[[1 2 3]
 [4 5 6]]


Math Operations

In [7]:
a+ 12

tensor([[13, 14, 15],
        [16, 17, 18]])

In [8]:
b+12

array([[13, 14, 15],
       [16, 17, 18]])

In [9]:
a*23

tensor([[ 23,  46,  69],
        [ 92, 115, 138]])

In [10]:
b*23

array([[ 23,  46,  69],
       [ 92, 115, 138]])

In [11]:
a**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [12]:
b**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [13]:
a%2

tensor([[1, 0, 1],
        [0, 1, 0]])

In [14]:
b%2

array([[1, 0, 1],
       [0, 1, 0]])

Element-wise Operation

In [15]:
a=torch.tensor([[1,2],[3,4]])
b=torch.tensor([[5,6],[7,8]])

x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

In [16]:
a,b

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))

In [17]:
x,y

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [18]:
a+b

tensor([[ 6,  8],
        [10, 12]])

In [19]:
x+y

array([[ 6,  8],
       [10, 12]])

In [20]:
a*b

tensor([[ 5, 12],
        [21, 32]])

In [21]:
x*y

array([[ 5, 12],
       [21, 32]])

In [22]:
a@b  # matrix multiplication

tensor([[19, 22],
        [43, 50]])

In [23]:
x@y

array([[19, 22],
       [43, 50]])

In [24]:
torch.matmul(a,b)

tensor([[19, 22],
        [43, 50]])

In [25]:
np.matmul(x,y)

array([[19, 22],
       [43, 50]])

In [26]:
a ** b

tensor([[    1,    64],
        [ 2187, 65536]])

In [27]:
x ** y

array([[    1,    64],
       [ 2187, 65536]])

In [28]:
a%b

tensor([[1, 2],
        [3, 4]])

In [29]:
x%y

array([[1, 2],
       [3, 4]])

In [30]:
a//b

tensor([[0, 0],
        [0, 0]])

In [31]:
x//y

array([[0, 0],
       [0, 0]])

In [32]:
# absolute

torch.abs(torch.tensor([-1,-2,-3]))

tensor([1, 2, 3])

In [33]:
np.abs(np.array([-1,-2,-3]))

array([1, 2, 3])

In [34]:
# negative 

torch.neg(torch.tensor([1,-2,3]))

tensor([-1,  2, -3])

In [35]:
np.negative(np.array([1,-2,3]))

array([-1,  2, -3])

In [36]:
-torch.tensor([1,-2,3])

tensor([-1,  2, -3])

In [37]:
-np.array([1,-2,3])

array([-1,  2, -3])

In [38]:
# round

torch.round(torch.tensor([1.4,-2.6,3.5]))

tensor([ 1., -3.,  4.])

In [39]:
np.round(np.array([1.4,-2.6,3.5]))

array([ 1., -3.,  4.])

In [40]:
# ceil

torch.ceil(torch.tensor([1.2,-2.3,3.4]))

tensor([ 2., -2.,  4.])

In [41]:
np.ceil(np.array([1.2,-2.3,3.4]))

array([ 2., -2.,  4.])

In [42]:
# floor

torch.floor(torch.tensor([1.2,-2.3,3.4]))

tensor([ 1., -3.,  3.])

In [43]:
np.floor(np.array([1.2,-2.3,3.4]))

array([ 1., -3.,  3.])

In [44]:
# exp

torch.exp(torch.tensor([1,2,3]))

tensor([ 2.7183,  7.3891, 20.0855])

In [45]:
np.exp(np.array([1,2,3]))

array([ 2.71828183,  7.3890561 , 20.08553692])

In [46]:
# clamp

torch.clamp(torch.tensor([1,-2,3]),min=-1,max=2)

tensor([ 1, -1,  2])

In [47]:
np.clip(np.array([1,-2,3]),min=-1,max=2)

array([ 1, -1,  2])

-------

In [48]:
a = torch.randint(low=0,high=10,size=(2,3),dtype=torch.float32)
b = np.random.randint(0,10,size=(2,3))
print(a)
print(b)

tensor([[0., 7., 1.],
        [7., 1., 8.]])
[[6 9 0]
 [4 4 6]]


In [49]:
# Sum
torch.sum(a)

tensor(24.)

In [50]:
np.sum(b)

np.int64(29)

In [51]:
# along axis 0 or columnwise or across rows
torch.sum(a,dim=0)

tensor([7., 8., 9.])

In [52]:
np.sum(b,axis=0)

array([10, 13,  6])

In [53]:
# along axis 1 or rowwise or across columns
torch.sum(a,dim=1)

tensor([ 8., 16.])

In [54]:
np.sum(b,axis=1)

array([15, 14])

In [55]:
torch.mean(a)        # only support float32 dtype

tensor(4.)

In [56]:
np.mean(b)

np.float64(4.833333333333333)

In [57]:
print(torch.min(a))
print(torch.max(a))
print(torch.argmin(a,keepdim=True))
print(torch.argmax(a))

tensor(0.)
tensor(8.)
tensor([[0]])
tensor(5)


In [58]:
a

tensor([[0., 7., 1.],
        [7., 1., 8.]])

In [59]:
print(np.min(b))
print(np.max(b))
print(np.argmin(b))
print(np.argmax(b))

0
9
2
1


In [60]:
torch.prod(a)

tensor(0.)

In [61]:
np.prod(b)

np.int64(0)

In [62]:
b

array([[6, 9, 0],
       [4, 4, 6]])

In [63]:
8*8*3*2*9

3456

In [64]:
torch.std(a)

tensor(3.6878)

In [65]:
torch.var(a)

tensor(13.6000)

In [66]:
np.std(b)

np.float64(2.733536577809454)

In [67]:
np.var(b)

np.float64(7.472222222222221)

In [68]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])

In [69]:
torch.stack((a,b))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [70]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [71]:
torch.transpose(torch.tensor([[1,2],[3,4],[5,6]]),0,1)

tensor([[1, 3, 5],
        [2, 4, 6]])

In [72]:
torch.transpose(torch.tensor([[1,2],[3,4],[5,6]]),1,0)

tensor([[1, 3, 5],
        [2, 4, 6]])

In [73]:
np.transpose([[1,2],[3,4],[5,6]])

array([[1, 3, 5],
       [2, 4, 6]])

In [74]:
a = torch.randint(0,12,(3,3),dtype=torch.float32)
a

tensor([[ 1.,  4., 10.],
        [ 3.,  2., 11.],
        [ 1., 11.,  0.]])

In [75]:
torch.det(a)

tensor(233.)

In [76]:
b=np.random.randint(0,12,(3,3))
b

array([[ 1,  6,  6],
       [ 4,  1,  3],
       [11,  4,  9]])

In [77]:
np.linalg.det(b)

np.float64(8.999999999999993)

In [78]:
torch.inverse(a)

tensor([[-0.5193,  0.4721,  0.1030],
        [ 0.0472, -0.0429,  0.0815],
        [ 0.1330, -0.0300, -0.0429]])

In [79]:
np.linalg.inv(b)

array([[-0.33333333, -3.33333333,  1.33333333],
       [-0.33333333, -6.33333333,  2.33333333],
       [ 0.55555556,  6.88888889, -2.55555556]])

In [80]:
torch.exp(a)

tensor([[2.7183e+00, 5.4598e+01, 2.2026e+04],
        [2.0086e+01, 7.3891e+00, 5.9874e+04],
        [2.7183e+00, 5.9874e+04, 1.0000e+00]])

In [81]:
np.exp(b)

array([[2.71828183e+00, 4.03428793e+02, 4.03428793e+02],
       [5.45981500e+01, 2.71828183e+00, 2.00855369e+01],
       [5.98741417e+04, 5.45981500e+01, 8.10308393e+03]])

In [82]:
torch.log(a)

tensor([[0.0000, 1.3863, 2.3026],
        [1.0986, 0.6931, 2.3979],
        [0.0000, 2.3979,   -inf]])

In [83]:
np.log(b)

array([[0.        , 1.79175947, 1.79175947],
       [1.38629436, 0.        , 1.09861229],
       [2.39789527, 1.38629436, 2.19722458]])

In [84]:
torch.sqrt(a)

tensor([[1.0000, 2.0000, 3.1623],
        [1.7321, 1.4142, 3.3166],
        [1.0000, 3.3166, 0.0000]])

In [85]:
np.sqrt(b)

array([[1.        , 2.44948974, 2.44948974],
       [2.        , 1.        , 1.73205081],
       [3.31662479, 2.        , 3.        ]])

In [86]:
torch.sigmoid(a)

tensor([[0.7311, 0.9820, 1.0000],
        [0.9526, 0.8808, 1.0000],
        [0.7311, 1.0000, 0.5000]])

In [87]:
# manually create for numpy

In [88]:
torch.softmax(a,dim=0)

tensor([[1.0651e-01, 9.1094e-04, 2.6894e-01],
        [7.8699e-01, 1.2328e-04, 7.3105e-01],
        [1.0651e-01, 9.9897e-01, 1.2210e-05]])

In [89]:
torch.relu(a)

tensor([[ 1.,  4., 10.],
        [ 3.,  2., 11.],
        [ 1., 11.,  0.]])

---------

### Inplace Operators

In [90]:
# some times we do not want to store results in a

m=torch.randint(0,12,(2,3),dtype=torch.float32)
n=torch.randint(0,12,(2,3),dtype=torch.float32)
print(m)
print(n)

tensor([[ 2.,  0.,  8.],
        [ 9., 10.,  3.]])
tensor([[ 3.,  7.,  1.],
        [ 5., 10.,  5.]])


In [91]:
m+n

tensor([[ 5.,  7.,  9.],
        [14., 20.,  8.]])

In [92]:
# the result of m+n will create a new tensor in menory
# some times we do not want to generate new tensor which consume extra memory
# to store result directly

m.add_(n)  # in-place operation
print(m)
print(n)

tensor([[ 5.,  7.,  9.],
        [14., 20.,  8.]])
tensor([[ 3.,  7.,  1.],
        [ 5., 10.,  5.]])


In [93]:
m.relu_()

tensor([[ 5.,  7.,  9.],
        [14., 20.,  8.]])

In [94]:
m

tensor([[ 5.,  7.,  9.],
        [14., 20.,  8.]])

-----------

### copy

In [95]:
a = torch.rand(2,3)
a

tensor([[0.1430, 0.5008, 0.6625],
        [0.0501, 0.8715, 0.6674]])

In [96]:
a

tensor([[0.1430, 0.5008, 0.6625],
        [0.0501, 0.8715, 0.6674]])

In [97]:
b=a

In [98]:
b

tensor([[0.1430, 0.5008, 0.6625],
        [0.0501, 0.8715, 0.6674]])

In [99]:
a[0][0] = 0

In [100]:
a

tensor([[0.0000, 0.5008, 0.6625],
        [0.0501, 0.8715, 0.6674]])

In [101]:
b

tensor([[0.0000, 0.5008, 0.6625],
        [0.0501, 0.8715, 0.6674]])

In [102]:
# result of b will automatically gets changes when we made changes to a

In [103]:
id(a)

140103449605888

In [104]:
id(b)

140103449605888

In [105]:
b=a.clone()

In [106]:
id(a)

140103449605888

In [107]:
id(b)

140103449605408

In [108]:
a

tensor([[0.0000, 0.5008, 0.6625],
        [0.0501, 0.8715, 0.6674]])

In [109]:
a[0][1]=0

In [110]:
a

tensor([[0.0000, 0.0000, 0.6625],
        [0.0501, 0.8715, 0.6674]])

In [111]:
b

tensor([[0.0000, 0.5008, 0.6625],
        [0.0501, 0.8715, 0.6674]])

In [112]:
x = np.random.randint(0,10,(2,3))

In [113]:
x

array([[4, 9, 6],
       [3, 9, 9]])

In [114]:
y=x

In [115]:
y

array([[4, 9, 6],
       [3, 9, 9]])

In [116]:
x[0][0]=0

In [117]:
x

array([[0, 9, 6],
       [3, 9, 9]])

In [118]:
y

array([[0, 9, 6],
       [3, 9, 9]])

In [119]:
y= x.copy()

In [120]:
x

array([[0, 9, 6],
       [3, 9, 9]])

In [121]:
x[0][1]=0

In [122]:
x

array([[0, 0, 6],
       [3, 9, 9]])

In [123]:
y

array([[0, 9, 6],
       [3, 9, 9]])

----------
### Running on cuda/GPU

In [ ]:
torch.cuda.is_available()

False

In [ ]:
device = torch.device('cuda')

In [ ]:
a = torch.rand(2,3,device=device)

In [ ]:
a+4

In [ ]:
# converting cpu tensors to gpu

b.to(device)

# b.to('cuda')

In [ ]:
# torch.cuda.synchronize()    # ensure the gpu operations are complete

----------
### Reshaping it

In [126]:
a= torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [127]:
a.reshape(2,8)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [128]:
a.reshape(2,2,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [130]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [137]:
# permute

In [131]:
a = torch.rand(2,3,4)
a

tensor([[[0.5019, 0.2694, 0.2403, 0.2791],
         [0.3079, 0.5353, 0.5004, 0.6180],
         [0.2774, 0.9508, 0.8611, 0.9555]],

        [[0.9866, 0.0317, 0.9024, 0.0418],
         [0.6137, 0.4217, 0.9873, 0.3521],
         [0.1412, 0.4232, 0.3299, 0.8921]]])

In [135]:
print(a.permute(2,0,1).shape)
a.permute(2,0,1)

torch.Size([4, 2, 3])


tensor([[[0.5019, 0.3079, 0.2774],
         [0.9866, 0.6137, 0.1412]],

        [[0.2694, 0.5353, 0.9508],
         [0.0317, 0.4217, 0.4232]],

        [[0.2403, 0.5004, 0.8611],
         [0.9024, 0.9873, 0.3299]],

        [[0.2791, 0.6180, 0.9555],
         [0.0418, 0.3521, 0.8921]]])

In [ ]:
print(a.permute(2,1,0).shape)       # shifting the shape
a.permute(2,1,0)

torch.Size([4, 3, 2])


tensor([[[0.5019, 0.9866],
         [0.3079, 0.6137],
         [0.2774, 0.1412]],

        [[0.2694, 0.0317],
         [0.5353, 0.4217],
         [0.9508, 0.4232]],

        [[0.2403, 0.9024],
         [0.5004, 0.9873],
         [0.8611, 0.3299]],

        [[0.2791, 0.0418],
         [0.6180, 0.3521],
         [0.9555, 0.8921]]])

In [ ]:
# unsqeeze  -> add extra dimension
print(a.shape)
print(a.unsqueeze(0).shape)
print(a.unsqueeze(1).shape)
print(a.unsqueeze(2).shape)
a.unsqueeze(0)

torch.Size([2, 3, 4])
torch.Size([1, 2, 3, 4])
torch.Size([2, 1, 3, 4])
torch.Size([2, 3, 1, 4])


tensor([[[[0.5019, 0.2694, 0.2403, 0.2791],
          [0.3079, 0.5353, 0.5004, 0.6180],
          [0.2774, 0.9508, 0.8611, 0.9555]],

         [[0.9866, 0.0317, 0.9024, 0.0418],
          [0.6137, 0.4217, 0.9873, 0.3521],
          [0.1412, 0.4232, 0.3299, 0.8921]]]])

In [144]:
# sqeeze  -> remove extra dimension
a = torch.rand(1,3,4)
print(a)
print(a.shape)
print(a.squeeze(0).shape)
print(a.squeeze(1).shape)
print(a.squeeze(2).shape)
a.squeeze(0)

tensor([[[0.6979, 0.9699, 0.2322, 0.0499],
         [0.5884, 0.6906, 0.8073, 0.6873],
         [0.6702, 0.7445, 0.2693, 0.7637]]])
torch.Size([1, 3, 4])
torch.Size([3, 4])
torch.Size([1, 3, 4])
torch.Size([1, 3, 4])


tensor([[0.6979, 0.9699, 0.2322, 0.0499],
        [0.5884, 0.6906, 0.8073, 0.6873],
        [0.6702, 0.7445, 0.2693, 0.7637]])

-------
### convert to numpy

In [145]:
a

tensor([[[0.6979, 0.9699, 0.2322, 0.0499],
         [0.5884, 0.6906, 0.8073, 0.6873],
         [0.6702, 0.7445, 0.2693, 0.7637]]])

In [146]:
a.numpy()

array([[[0.6978548 , 0.9699058 , 0.23221868, 0.04987007],
        [0.5884045 , 0.6906338 , 0.8072767 , 0.6873222 ],
        [0.67023325, 0.7445428 , 0.2693113 , 0.7636768 ]]], dtype=float32)

In [148]:
c=np.random.rand(2,3)
torch.from_numpy(c)

tensor([[0.8230, 0.2186, 0.6577],
        [0.6152, 0.5738, 0.4863]], dtype=torch.float64)