In [ ]:
import numpy as np
import plotly.graph_objects as go

In [10]:
x=np.arange(0,10)
y=np.copy(x)
x,y=np.meshgrid(x,y,indexing='ij')
z=(x**2+y**2)**0.5

fig=go.Figure(data=[go.Surface(z=z,x=x,y=y)])
fig.show()

In [3]:
x.shape,y.shape,z.shape

((10, 10), (10, 10), (10, 10))

In [4]:
x[0],y[0],z[0]

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [5]:
x[1],y[1],z[1]

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [6]:
x[2],y[2],z[2]

(array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))

In [7]:
x=np.linspace(-10,10,1000)
y=np.copy(x)
z=np.sin(np.sqrt(x**2+y**2))

fig=go.Figure(data=[go.Scatter3d(z=z,x=x,y=y,mode="markers",marker=dict(size=1))])
fig.show()

In [8]:
x.shape,y.shape,z.shape

((1000,), (1000,), (1000,))

In [9]:
x=np.linspace(-10,10,100)
y=np.copy(x)
x,y=np.meshgrid(x,y)
z=np.sin(np.sqrt(x**2+y**2))

fig=go.Figure(data=[go.Scatter3d(z=z.ravel(),x=x.ravel(),y=y.ravel(),mode="markers",marker=dict(size=1,color=z.ravel(),colorscale='rainbow'))])
fig.show()